[package]
name = "pinreq"
version = "0.1.0"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]
edition = "2018"

[[bin]]
name = "pinreq-pubsub"
path = "src/pinreq_pubsub.rs"

[[bin]]
name = "pinreq-matrix"
path = "src/pinreq_matrix.rs"

[dependencies]
base58 = "0.1.0"
base64 = "0.10.0"
clap = "2.32"
env_logger = "0.6"
failure = "0.1.5"
futures = "0.1"
gpgme = "0.8.0"
hyper = "0.12.23"
ipfs-api="0.5.0-alpha"
log = "0.4"
rpassword = "2.1.0"
ruma-client = {path = "../ruma-client"}
ruma-events = "0.11.0"
tokio = "0.1"
